apiVersion: apps/v1
kind: Deployment
metadata:
  name: applicants.api
spec:
  selector:
    matchLabels:
      app: applicants.api
  template:
    metadata:
      labels:
        app: applicants.api
    spec:
      containers:
      - name: applicants.api
        image: pvdbleek/applicants.api
        ports:
        - containerPort: 8081
        env:
          - name: ConnectionString
            value: Server=10.0.0.123;User=sa;Password=Wachtwoord123!;Database=dotnetgigs.applicants;
---
apiVersion: v1
kind: Service
metadata:
  name: applicants.api
spec:
  type: ClusterIP
  selector:
    app: applicants.api
  ports:
  - name: http
    port: 80
    targetPort: 8081
