apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api
spec:
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      containers:
      - name: identity-api
        image: pvdbleek/identity-api
        ports:
        - containerPort: 80
        env:
          - name: RedisHost
            value: user-data:6379
---
apiVersion: v1
kind: Service
metadata:
  name: identity-api
spec:
  type: ClusterIP
  selector:
    app: identity-api
  ports:
  - name: http
    port: 80
    targetPort: 80
